# -*- coding: utf-8 -*-
# Generated by Django 1.9.1 on 2016-01-05 22:38
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pythonnest', '0002_auto_20141005_2218'),
    ]

    operations = [
        migrations.AlterField(
            model_name='release',
            name='classifiers',
            field=models.ManyToManyField(blank=True, db_index=True, to='pythonnest.Classifier'),
        ),
        migrations.AlterField(
            model_name='release',
            name='obsoletes',
            field=models.ManyToManyField(blank=True, db_index=True, related_name='dep_obsoletes', to='pythonnest.Dependence'),
        ),
        migrations.AlterField(
            model_name='release',
            name='obsoletes_dist',
            field=models.ManyToManyField(blank=True, db_index=True, related_name='dep_obsoletes_dist', to='pythonnest.Dependence'),
        ),
        migrations.AlterField(
            model_name='release',
            name='provides',
            field=models.ManyToManyField(blank=True, db_index=True, related_name='dep_provides', to='pythonnest.Dependence'),
        ),
        migrations.AlterField(
            model_name='release',
            name='provides_dist',
            field=models.ManyToManyField(blank=True, db_index=True, related_name='dep_provides_dist', to='pythonnest.Dependence'),
        ),
        migrations.AlterField(
            model_name='release',
            name='requires',
            field=models.ManyToManyField(blank=True, db_index=True, related_name='dep_requires', to='pythonnest.Dependence'),
        ),
        migrations.AlterField(
            model_name='release',
            name='requires_dist',
            field=models.ManyToManyField(blank=True, db_index=True, related_name='dep_requires_dist', to='pythonnest.Dependence'),
        ),
        migrations.AlterField(
            model_name='release',
            name='requires_external',
            field=models.ManyToManyField(blank=True, db_index=True, related_name='dep_requires_external', to='pythonnest.Dependence'),
        ),
        migrations.AlterField(
            model_name='release',
            name='requires_python',
            field=models.ManyToManyField(blank=True, db_index=True, related_name='dep_requires_python', to='pythonnest.Dependence'),
        ),
    ]
