# Generated by Django 2.0.4 on 2018-04-21 08:00

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    dependencies = [
        ('pythonnest', '0004_auto_20160117_1805'),
    ]

    operations = [
        migrations.AlterField(
            model_name='package',
            name='group',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL,
                                    to='auth.Group', verbose_name='restrict to this group'),
        ),
    ]
